
set(FILES
    Source/Tools/HoudiniEngineEditorSystemComponent.cpp
    Source/Tools/HoudiniEngineEditorSystemComponent.h
    Source/AssetContainer.h
    Source/ExtractPoints.h
    Source/ExtractPoints.cpp
    Source/ExtractPoints.ui
    Source/OperatorSelection.h
    Source/OperatorSelection.cpp
    Source/OperatorSelection.ui
    Source/HoudiniStatusPanel.h
    Source/HoudiniStatusPanel.cpp
    Source/HoudiniStatusPanel.ui
    Source/StdAfx.cpp
    Source/StdAfx.h
    SideFX/HE_ParameterWidget.cpp
	SideFX/HE_ParameterWidget.h
	SideFX/HE_ParameterWidget_Button.cpp
	SideFX/HE_ParameterWidget_Button.h
	SideFX/HE_ParameterWidget_Float.cpp
	SideFX/HE_ParameterWidget_Float.h
	SideFX/HE_ParameterWidget_Folder.cpp
	SideFX/HE_ParameterWidget_Folder.h
	SideFX/HE_ParameterWidget_FolderList.cpp
	SideFX/HE_ParameterWidget_FolderList.h
	SideFX/HE_ParameterWidget_Integer.cpp
	SideFX/HE_ParameterWidget_Integer.h
	SideFX/HE_ParameterWidget_IntegerChoice.cpp
	SideFX/HE_ParameterWidget_IntegerChoice.h
	SideFX/HE_ParameterWidget_Label.cpp
	SideFX/HE_ParameterWidget_Label.h
	SideFX/HE_ParameterWidget_Multi.cpp
	SideFX/HE_ParameterWidget_Multi.h
	SideFX/HE_ParameterWidget_MultiInstance.cpp
	SideFX/HE_ParameterWidget_MultiInstance.h
	SideFX/HE_ParameterWidget_String.cpp
	SideFX/HE_ParameterWidget_String.h
	SideFX/HE_ParameterWidget_StringChoice.cpp
	SideFX/HE_ParameterWidget_StringChoice.h
	SideFX/HE_ParameterWidget_Toggle.cpp
	SideFX/HE_ParameterWidget_Toggle.h
	SideFX/HE_Viewer.cpp
	SideFX/HE_Viewer.h
    Components/HoudiniAssetComponent.h
    Components/HoudiniAssetComponent.cpp
    Components/HoudiniCurveAttributeComponent.h
    Components/HoudiniCurveAttributeComponent.cpp
    Components/HoudiniFbxConfig.h
    Components/HoudiniFbxConfig.cpp
    Components/HoudiniNodeExporter.h
    Components/HoudiniNodeExporter.cpp
    Components/HoudiniTerrainComponent.h
    Components/HoudiniTerrainComponent.cpp
    Components/HoudiniScatterComponent.h
    Components/HoudiniScatterComponent.cpp
    Source/HoudiniCommon.h
    Source/Houdini.h
    Source/Houdini.cpp
    Source/HoudiniAsset.h
    Source/HoudiniAsset.cpp
    Source/HoudiniEngineString.h
    Source/HoudiniEngineString.cpp
    Source/HoudiniEngineUtils.h
    Source/HoudiniEngineUtils.cpp
    Source/HoudiniNode.h
    Source/HoudiniNode.cpp
    Source/HoudiniParameter.h
    Source/HoudiniParameter.cpp
    Source/HoudiniPropertyGroup.h
    Source/HoudiniPropertyGroup.cpp
    Source/HoudiniPropertyHandlers.h
    Source/HoudiniPropertyHandlers.cpp
    Source/HoudiniPaintAttribTool.h
    Source/HoudiniPaintAttribTool.cpp
    Source/HoudiniScriptProperties.h
    Source/HoudiniScriptProperties.cpp
    Source/HoudiniSplineTranslator.h
    Source/HoudiniSplineTranslator.cpp
    Source/HoudiniTerrain.h
    Source/HoudiniTerrain.cpp
    Source/InputNodeManager.h
    Source/InputNodeManager.cpp
    Source/HoudiniMaterialTranslator.h
    Source/HoudiniMaterialTranslator.cpp
    Components/HoudiniNodeComponentConfig.h
    Components/HoudiniNodeComponentConfig.cpp
    
)
